-- ============================================================
-- TABLA: comisarias_pnp
-- Prontuario telefónico - Regiones: Tumbes, La Libertad,
-- Lambayeque, Amazonas, Piura
-- ============================================================

CREATE TABLE IF NOT EXISTS comisarias_pnp (
    id BIGSERIAL PRIMARY KEY,
    region TEXT NOT NULL,
    comando_superior TEXT NOT NULL,
    nombre TEXT NOT NULL,
    tipo TEXT,
    categoria TEXT,
    direccion TEXT,
    distrito TEXT,
    provincia TEXT,
    departamento TEXT,
    telefono TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices útiles
CREATE INDEX IF NOT EXISTS idx_comisarias_region ON comisarias_pnp(region);
CREATE INDEX IF NOT EXISTS idx_comisarias_departamento ON comisarias_pnp(departamento);
CREATE INDEX IF NOT EXISTS idx_comisarias_nombre ON comisarias_pnp(nombre);

-- ============================================================
-- DATOS: FRENTE POLICIAL TUMBES
-- ============================================================
INSERT INTO comisarias_pnp (region, comando_superior, nombre, tipo, categoria, direccion, distrito, provincia, departamento, telefono) VALUES
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comando', NULL, 'Av. Tumbes 1033, Auxiliar Panamericana Norte', 'Tumbes', 'Tumbes', 'Tumbes', '980-122-459'),
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comisaría PNP San José', 'Comisaría', 'A', 'Esq. Calle Zarumilla N° 301', 'Tumbes', 'Tumbes', 'Tumbes', '980-122-460'),
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comisaría PNP Rural Corrales', 'Comisaría Rural', 'B', 'Calle San Pedro N° 600', 'Corrales', 'Tumbes', 'Tumbes', '945-093-992'),
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comisaría PNP Rural Sectorial Zorritos', 'Comisaría Rural Sectorial', 'B', 'Av. Republica del Perú S/N (Frente Al Coliseo)', 'Zorritos', 'Contralmirante Villar', 'Tumbes', '980-121-633'),
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comisaría PNP San Juan de la Virgen', 'Comisaría', 'D', 'Francisco Ibáñez S/N', 'San Juan de la Virgen', 'Tumbes', 'Tumbes', '964-611-521'),
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comisaría PNP Pampa Grande', 'Comisaría', 'E', 'Av. Simón Bolívar Mz. U Lote. 8', 'Tumbes', 'Tumbes', 'Tumbes', '957-822-065'),
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comisaría PNP Rural Sectorial Pampas de Hospital', 'Comisaría Rural Sectorial', 'C', 'Av. Alipio Rosales y Plaza Armas Pampas de Hospital', 'Pampa de Hospital', 'Tumbes', 'Tumbes', '945-332-916'),
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comisaría PNP Rural San Jacinto', 'Comisaría Rural', 'D', 'Calle Horacio Patiño N° 531', 'San Jacinto', 'Tumbes', 'Tumbes', '964-596-404'),
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comisaría PNP Rural Sectorial Zarumilla', 'Comisaría Rural Sectorial', 'A', 'Calle Tumbes N° 324', 'Zarumilla', 'Zarumilla', 'Tumbes', '980-121-632'),
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comisaría PNP Rural Aguas Verdes', 'Comisaría Rural', 'B', 'Av. Republica del Perú N° 298', 'Aguas Verdes', 'Zarumilla', 'Tumbes', '957-822-184'),
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comisaría PNP Rural Papayal', 'Comisaría Rural', 'C', 'Calle San Martin N° 303', 'Papayal', 'Zarumilla', 'Tumbes', '964-611-657'),
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comisaría PNP Rural La Cruz', 'Comisaría Rural', 'C', 'Calle Piura N° 422', 'La Cruz', 'Tumbes', 'Tumbes', '945-328-618'),
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comisaría PNP Rural San Isidro', 'Comisaría Rural', 'D', 'Calle Los Algarrobos S/N', 'Corrales', 'Tumbes', 'Tumbes', '945-330-744'),
('Frente Policial Tumbes', 'Frente Policial Tumbes', 'Comisaría PNP Rural Cancas', 'Comisaría Rural', 'C', 'Av. Panamericana Norte "Barrio Centro"', 'Canoas de Punta Sal', 'Contralmirante Villar', 'Tumbes', '945-327-819');

-- ============================================================
-- DATOS: REGPOL LA LIBERTAD
-- ============================================================
INSERT INTO comisarias_pnp (region, comando_superior, nombre, tipo, categoria, direccion, distrito, provincia, departamento, telefono) VALUES
('Región Policial La Libertad', 'REGPOL La Libertad', 'REGPOL La Libertad', 'Comando', NULL, 'Jr. Diego De Almagro S/N Centro Histórico', 'Trujillo', 'Trujillo', 'La Libertad', '980-122-400'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Familia Trujillo', 'Comisaría Familia', NULL, 'Jr. Marcial Acharan con Ciro Alegría N° 184 Urb. Las Quintanas', 'Trujillo', 'Trujillo', 'La Libertad', '964-598-248'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP La Noria', 'Comisaría', 'A', 'Av. América Sur N° 405-413 Urb. La Noria', 'Trujillo', 'Trujillo', 'La Libertad', '957-822-960'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Ayacucho', 'Comisaría', 'A', 'Jr. Ayacucho N° 458 Centro Histórico', 'Trujillo', 'Trujillo', 'La Libertad', '980-121-593'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP El Alambre', 'Comisaría', 'A', 'Jr. Pedro Muñís / Porto Alegre Urb. El Alambre', 'Trujillo', 'Trujillo', 'La Libertad', '945-092-219'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Huanchaco', 'Comisaría Rural', 'C', 'Av. La Rivera/Colon', 'Huanchaco', 'Trujillo', 'La Libertad', '980-122-305'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural El Milagro', 'Comisaría Rural', 'B', 'Túpac Amaru Mz. LL Lote. 01', 'Huanchaco', 'Trujillo', 'La Libertad', '945-093-588'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Bellavista', 'Comisaría', 'B', 'Calle 22 de febrero N° 803 Parte Alta', 'La Esperanza', 'Trujillo', 'La Libertad', '957-820-147'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Nicolas Alcázar', 'Comisaría', 'B', 'Jr. Cahuide N° 342', 'El Porvenir', 'Trujillo', 'La Libertad', '980-121-079'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP La Esperanza Jerusalén', 'Comisaría', 'A', 'Mz. 34 Lote.01 AA.HH Wichanzao', 'La Esperanza', 'Trujillo', 'La Libertad', '980-121-573'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Sectorial Sánchez Carrión', 'Comisaría Sectorial', 'A', 'Av. Sánchez Carrión N° 1100 Simón Bolívar', 'El Porvenir', 'Trujillo', 'La Libertad', '945-315-731'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Salaverry', 'Comisaría Rural', 'C', 'Calle Libertad N° 299', 'Salaverry', 'Trujillo', 'La Libertad', '959-401-110'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Florencia de Mora', 'Comisaría Rural', 'B', 'Calle 26 de Julio Cdra. 11 Parque Santa Rosa', 'Florencia de Mora', 'Trujillo', 'La Libertad', '957-825-049'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Alto Trujillo', 'Comisaría Rural', 'B', 'Mz. "P" Lt. 1-A Barrio 2', 'Trujillo', 'Trujillo', 'La Libertad', '945-093-495'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Sectorial Moche', 'Comisaría Rural Sectorial', 'B', 'Av. La Marina S/N', 'Moche', 'Trujillo', 'La Libertad', '957-822-434'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Miramar', 'Comisaría Rural', 'C', 'Av. Santa María Mz. 30 Lt. 1-A', 'Moche', 'Trujillo', 'La Libertad', '957-876-564'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Sectorial Laredo', 'Comisaría Rural Sectorial', 'B', 'Pasaje La Fortuna S/N', 'Laredo', 'Trujillo', 'La Libertad', '957-825-372'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Poroto', 'Comisaría Rural', 'E', 'Calle San Martin N° 107', 'Poroto', 'Trujillo', 'La Libertad', '980-121-460'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Simbal', 'Comisaría Rural', 'E', 'Jr. Porvenir N° 211', 'Simbal', 'Trujillo', 'La Libertad', '980-122-174'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Sectorial Otuzco', 'Comisaría Rural Sectorial', 'B', 'Jr. Progreso N° 388', 'Otuzco', 'Otuzco', 'La Libertad', '980-121-575'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Samne', 'Comisaría', 'E', 'Calle Los Libertadores S/N', 'Otuzco', 'Otuzco', 'La Libertad', '957-822-219'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Sinsicap', 'Comisaría Rural', 'D', 'Jr. Bermúdez S/N', 'Sinsicap', 'Otuzco', 'La Libertad', '957-822-285'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Usquil', 'Comisaría Rural', 'D', 'Jr. Arica S/N', 'Usquil', 'Otuzco', 'La Libertad', '980-122-400'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Huaranchal', 'Comisaría Rural', 'E', 'Calle San Martín N° 035', 'Huaranchal', 'Otuzco', 'La Libertad', '980-122-400'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Carabamba', 'Comisaría Rural', 'E', 'Calle Unión 119', 'Carabamba', 'Julcán', 'La Libertad', '980-122-400'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Mache', 'Comisaría Rural', 'E', 'Av. Campo Bello S/N', 'Mache', 'Otuzco', 'La Libertad', '957-822-540'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Sectorial Viru', 'Comisaría Rural Sectorial', 'B', 'Av. Virú N° 125', 'Viru', 'Viru', 'La Libertad', '964-598-792'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Julcán', 'Comisaría', 'C', 'Av. Luis Felipe de la Puente N° 234 y La Cultura', 'Julcán', 'Julcán', 'La Libertad', '942-068-855'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Víctor Raúl Haya de la Torre', 'Comisaría Rural', 'C', 'Calle Cesar Vallejo Mz. 01 Lt. 37', 'Viru', 'Viru', 'La Libertad', '964-598-395'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Guadalupito', 'Comisaría', 'D', 'Jr. Unión Mz. H Lt. 01', 'Guadalupito', 'Viru', 'La Libertad', '964-597-879'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Sectorial Paiján', 'Comisaría Rural Sectorial', 'A', 'Sector. Jorge Chávez Mz 16 Lote 1', 'Paiján', 'Ascope', 'La Libertad', '957-823-012'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Chocope', 'Comisaría Rural', 'C', 'Jr. Bolognesi N° 196', 'Chocope', 'Ascope', 'La Libertad', '959-291-018'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Razuri', 'Comisaría Rural', 'C', 'Calle Alfonso Ugarte N° 623', 'Razuri', 'Ascope', 'La Libertad', '980-122-258'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Santiago de Cao', 'Comisaría Rural', 'D', 'Calle Libertad N° 445', 'Santiago de Cao', 'Ascope', 'La Libertad', '957-822-907'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Casa Grande', 'Comisaría Rural', 'C', 'Calle Independencia N° 224', 'Casa Grande', 'Ascope', 'La Libertad', '942-439-829'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Cartavio', 'Comisaría Rural', 'C', 'Calle Real S/N', 'Santiago de Cao', 'Ascope', 'La Libertad', '980-121-097'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Chiclin', 'Comisaría Rural', 'D', 'Calle Progreso N° 49', 'Chiclin', 'Ascope', 'La Libertad', '964-598-528'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Sectorial Cascas – Gran Chimú', 'Comisaría Rural Sectorial', 'C', 'Jr. 28 de Julio Cdra. 08', 'Cascas', 'Gran Chimú', 'La Libertad', '945-092-942'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Sausal', 'Comisaría Rural', 'D', 'Calle Casa Grande y Piura S/N', 'Chicama', 'Ascope', 'La Libertad', '942-067-150'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Punta Moreno', 'Comisaría Rural', 'D', 'Av. Roger Castillo Valderrama S/N', 'Cascas', 'Gran Chimú', 'La Libertad', '980-122-400'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Compín', 'Comisaría Rural', 'E', 'Calle Mendelevio N° 402', 'Marmot', 'Gran Chimú', 'La Libertad', '980-122-400'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Lucma', 'Comisaría Rural', 'E', 'Calle Lima S/N', 'Lucma', 'Gran Chimú', 'La Libertad', '980-122-400'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural San Pedro de Lloc', 'Comisaría Rural', 'B', 'Calle Razuri S/N', 'San Pedro de Lloc', 'Pacasmayo', 'La Libertad', '980-121-369'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Guadalupe', 'Comisaría Rural', 'B', 'Av. Nila Zerruty Mz. 20 Lt. 25', 'Guadalupe', 'Pacasmayo', 'La Libertad', '964-595-750'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Ciudad de Dios', 'Comisaría Rural', 'C', 'Av. Republica de Alemania N° 303', 'Guadalupe', 'Pacasmayo', 'La Libertad', '980-122-320'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Sectorial Pacasmayo', 'Comisaría Rural Sectorial', 'A', 'Calle dos de Mayo N° 05', 'Pacasmayo', 'Pacasmayo', 'La Libertad', '980-121-576'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Jequetepeque', 'Comisaría Rural', 'D', 'Jr. San José N° 451', 'Jequetepeque', 'Pacasmayo', 'La Libertad', '957-823-102'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Chepén', 'Comisaría Rural', 'B', 'Calle Pacasmayo N° 471', 'Chepén', 'Chepén', 'La Libertad', '959-290-022'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Talambo', 'Comisaría Rural', 'E', 'Av. Miraflores S/N', 'Chepén', 'Chepén', 'La Libertad', '980-122-399'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Pacanga', 'Comisaría Rural', 'D', 'Jr. Ayacucho N° 798', 'Pacanga', 'Chepén', 'La Libertad', '957-824-545'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Huamachuco', 'Comisaría Rural', 'A', 'Av. Sánchez Carrión Cuadra. 12', 'Huamachuco', 'Sánchez Carrión', 'La Libertad', '980-121-574'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Santiago de Chuco', 'Comisaría Rural', 'B', 'Av. Miguel Grau N° 1267', 'Santiago de Chuco', 'Santiago de Chuco', 'La Libertad', '980-122-400'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Curgos', 'Comisaría Rural', 'E', 'Calle Progreso S/N', 'Curgo', 'Sánchez Carrión', 'La Libertad', '957-823-379'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Sarin', 'Comisaría Rural', 'E', 'Calle Serpaquino N° 111', 'Sarin', 'Sánchez Carrión', 'La Libertad', '957-824-931'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Angasmarca', 'Comisaría Rural', 'E', 'Av. Pablo Porturas N° 112', 'Angasmarca', 'Santiago de Chuco', 'La Libertad', '980-122-400'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Tayabamba Pataz', 'Comisaría Rural', 'C', 'Calle 02 de Mayo S/N', 'Tayabamba', 'Pataz', 'La Libertad', '957-825-194'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Cachicadan', 'Comisaría Rural', 'E', 'Calle Wenceslao Gálvez S/N', 'Cachicadan', 'Santiago de Chuco', 'La Libertad', '980-122-400'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Chillia', 'Comisaría Rural', 'D', 'Calle Cesar Vallejo S/N', 'Chillia', 'Pataz', 'La Libertad', '980-122-400'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Chagual', 'Comisaría Rural', 'D', 'Carretera Principal A Retamas S/N', 'Chagual', 'Pataz', 'La Libertad', '964-598-428'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Retamas', 'Comisaría Rural', 'D', 'Calle Retamas S/N', 'Parcoy', 'Pataz', 'La Libertad', '980-122-400'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Llacuabamba', 'Comisaría Rural', 'D', 'Calle Las Chilcas – Llacuabamba', 'Parcoy', 'Pataz', 'La Libertad', '980-122-400'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Bambamarca', 'Comisaría Rural', 'E', 'Calle San Isidro S/N Plaza de Armas', 'Bambamarca', 'Bolívar', 'La Libertad', '957-687-211'),
('Región Policial La Libertad', 'REGPOL La Libertad', 'Comisaría PNP Rural Bolívar', 'Comisaría Rural', 'E', 'Jr. Bolívar N° 402', 'Bolívar', 'Bolívar', 'La Libertad', '957-689-862');

-- ============================================================
-- DATOS: REGPOL LAMBAYEQUE
-- ============================================================
INSERT INTO comisarias_pnp (region, comando_superior, nombre, tipo, categoria, direccion, distrito, provincia, departamento, telefono) VALUES
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'REGPOL Lambayeque', 'Comando', NULL, 'Calle San José 1099', 'Chiclayo', 'Chiclayo', 'Lambayeque', '657-804-683'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Cesar Llatas Castro', 'Comisaría', 'A', 'Vicente de la Vega N° 1182', 'Chiclayo', 'Chiclayo', 'Lambayeque', '943-088-767'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP José Leonardo Ortiz', 'Comisaría', 'A', 'Av. Argentina N° 2251', 'José Leonardo Ortiz', 'Chiclayo', 'Lambayeque', '943-089-623'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP La Victoria', 'Comisaría', 'A', 'Av. Pachacútec N° 1510', 'La Victoria', 'Chiclayo', 'Lambayeque', '943-094-157'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Del Norte', 'Comisaría', 'B', 'Francisco Cuneo Salazar N° 1101', 'Chiclayo', 'Chiclayo', 'Lambayeque', '943-090-417'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Campodónico', 'Comisaría', 'B', 'Av. Jorge Chávez N° 801', 'Chiclayo', 'Chiclayo', 'Lambayeque', '943-091-983'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Pimentel', 'Comisaría Rural', 'C', 'Av. Miguel Grau N° 113', 'Pimentel', 'Chiclayo', 'Lambayeque', '980-121-563'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Chongoyape', 'Comisaría Rural', 'C', 'Calle Simón Bolívar N° 2520', 'Chongoyape', 'Chiclayo', 'Lambayeque', '980-122-240'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Sectorial Lambayeque', 'Comisaría Sectorial', 'A', 'Calle 2 de Mayo N° 316', 'Lambayeque', 'Lambayeque', 'Lambayeque', '943-893-443'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural San Martin de Porras', 'Comisaría Rural', 'B', 'Calle Capitán Orbegoso S/N', 'Lambayeque', 'Lambayeque', 'Lambayeque', '980-121-566'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Mórrope', 'Comisaría', 'C', 'Calle Francisco Bolognesi N° 492', 'Mórrope', 'Lambayeque', 'Lambayeque', '943-898-594'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Cruz del Médano', 'Comisaría Rural', 'D', 'Calle Elías Aguirre N° 189 Centro Poblado Cruz de Médano', 'Morrope', 'Lambayeque', 'Lambayeque', '942-099-866'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Mochumi', 'Comisaría Rural', 'D', 'Av. José de San Martin Cuadra 4', 'Mochumí', 'Lambayeque', 'Lambayeque', '957-806-194'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Jayanca', 'Comisaría Rural', 'C', 'Calle Elías Aguirre N° 405', 'Jayanca', 'Lambayeque', 'Lambayeque', '980-122-294'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural San José', 'Comisaría Rural', 'D', 'Calle Miguel Grau 363', 'San José', 'Lambayeque', 'Lambayeque', '943-888-480'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Túcume', 'Comisaría Rural', 'C', 'Carretera Fernando Belaúnde Terry 266', 'Túcume', 'Lambayeque', 'Lambayeque', '657-804-683'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Íllimo', 'Comisaría Rural', 'D', 'Calle San Juan N° 248', 'Íllimo', 'Lambayeque', 'Lambayeque', '957-806-408'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Pacora', 'Comisaría Rural', 'D', 'Av. San Pablo N° 131 Carretera Fernando Belaúnde Terry', 'Pacora', 'Lambayeque', 'Lambayeque', '943-897-829'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Sectorial Monsefú', 'Comisaría Rural Sectorial', 'B', 'Calle 7 de Junio N° 521', 'Monsefú', 'Chiclayo', 'Lambayeque', '980-122-225'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Reque', 'Comisaría Rural', 'C', 'Calle Diego Ferre N° 100', 'Reque', 'Chiclayo', 'Lambayeque', '943-877-303'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Santa Rosa', 'Comisaría Rural', 'D', 'Av. Mariscal Castilla 901', 'Santa Rosa', 'Chiclayo', 'Lambayeque', '980-122-324'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Ciudad Eten', 'Comisaría Rural', 'D', 'Calle Pedro Ruiz Gallo 692', 'Eten', 'Chiclayo', 'Lambayeque', '943-894-157'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Puerto Eten', 'Comisaría Rural', 'D', 'Calle Diego Ferre', 'Puerto Eten', 'Chiclayo', 'Lambayeque', '957-803-955'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Mocupe', 'Comisaría Rural', 'C', 'Av. Independencia N° 445 Lagunas', 'Lagunas', 'Chiclayo', 'Lambayeque', '943-893-035'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Sectorial Cayaltí', 'Comisaría Rural Sectorial', 'B', 'Av. 9 de Octubre N° 110', 'Cayaltí', 'Chiclayo', 'Lambayeque', '943-895-877'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Oyotun', 'Comisaría Rural', 'D', 'Calle Francisco Bolognesi N° 449', 'Oyotún', 'Chiclayo', 'Lambayeque', '957-806-521'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Zaña', 'Comisaría Rural', 'D', 'Calle Real N° 450', 'Zaña', 'Chiclayo', 'Lambayeque', '964-597-721'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Nueva Arica', 'Comisaría Rural', 'D', 'Calle Miguel Grau N° 891', 'Nueva Arica', 'Chiclayo', 'Lambayeque', '957-803-457'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Sectorial Tumán', 'Comisaría Rural Sectorial', 'B', 'Av. Ramon Castilla N° 418', 'Tumán', 'Chiclayo', 'Lambayeque', '943-891-885'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Posope Alto', 'Comisaría Rural', 'C', 'Calle Santa Rosa N° 398 Posope Alto', 'Posope Alto', 'Chiclayo', 'Lambayeque', '943-087-550'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Pomalca', 'Comisaría Rural', 'C', 'Av. Apolinario Salcedo S/N PE-6A', 'Pomalca', 'Chiclayo', 'Lambayeque', '943-895-255'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Pátapo', 'Comisaría Rural', 'C', 'Calle Fabrica S/N', 'Pátapo', 'Chiclayo', 'Lambayeque', '980-122-247'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Pucalá', 'Comisaría Rural', 'C', 'Frente a la Plaza de Armas', 'Pomalca', 'Chiclayo', 'Lambayeque', '980-122-264'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Saltur', 'Comisaría Rural', 'C', 'Av. Pomalca S/N', 'Saltur', 'Chiclayo', 'Lambayeque', '980-121-958'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Calupe', 'Comisaría Rural', 'D', 'Av. Real S/N', 'Calupe', 'Chiclayo', 'Lambayeque', '957-804-960'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Sectorial Olmos', 'Comisaría Rural Sectorial', 'B', 'Av. Augusto B. Leguía N° 430', 'Olmos', 'Lambayeque', 'Lambayeque', '980-122-236'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Motupe', 'Comisaría Rural', 'C', 'Av. Primavera N° 477', 'Motupe', 'Lambayeque', 'Lambayeque', '980-122-402'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Penachi', 'Comisaría Rural', 'D', 'Av. Cruz de Yanahuanca S/N Pueblo de Penachí', 'Salas', 'Lambayeque', 'Lambayeque', '657-804-683'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Sectorial Ferreñafe', 'Comisaría Rural Sectorial', 'A', 'Av. Tacna N° 720', 'Ferreñafe', 'Ferreñafe', 'Lambayeque', '943-890-961'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Batan Grande', 'Comisaría Rural', 'D', 'Calle Culpon N° 16', 'Pitipo', 'Ferreñafe', 'Lambayeque', '957-806-462'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Cañaris', 'Comisaría Rural', 'D', 'Calle Alcides Sánchez Carrión', 'Cañaris', 'Ferreñafe', 'Lambayeque', '657-804-683'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Uyurpampa', 'Comisaría Rural', 'E', 'Calle Víctor Muro Mz. O Lote 08 Incahuasi', 'Incahuasi', 'Ferreñafe', 'Lambayeque', '657-804-683'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Incahuasi', 'Comisaría Rural', 'D', 'Calle Unión S/N', 'Incahuasi', 'Ferreñafe', 'Lambayeque', '657-804-683'),
('Región Policial Lambayeque', 'REGPOL Lambayeque', 'Comisaría PNP Rural Picsi', 'Comisaría Rural', 'C', 'Calle Sta. Ana 300', 'Picsi', 'Chiclayo', 'Lambayeque', '943-891-374');

-- ============================================================
-- DATOS: REGPOL AMAZONAS
-- ============================================================
INSERT INTO comisarias_pnp (region, comando_superior, nombre, tipo, categoria, direccion, distrito, provincia, departamento, telefono) VALUES
('Región Policial Amazonas', 'REGPOL Amazonas', 'REGPOL Amazonas', 'Comando', NULL, 'Jr. Ayacucho N° 1040', 'Chachapoyas', 'Chachapoyas', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Familia Chachapoyas', 'Comisaría Familia', NULL, 'Jr. Libertad N° 1074', 'Chachapoyas', 'Chachapoyas', 'Amazonas', '943-796-153'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Sectorial Chachapoyas', 'Comisaría Rural Sectorial', 'A', 'Jr. Amazonas Cdra 12', 'Chachapoyas', 'Chachapoyas', 'Amazonas', '964-773-832'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Chuquibamba', 'Comisaría Rural', 'E', 'Jr. San Martin S/N', 'Chachapoyas', 'Chachapoyas', 'Amazonas', '957-815-709'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural San Francisco de Dagua Pipus', 'Comisaría Rural', 'D', 'Av. Pipus N° 660', 'San Francisco de Dagua Pipus', 'Chachapoyas', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Molinopampa', 'Comisaría Rural', 'D', 'Jr. Independencia N° 380', 'Molinopampa', 'Chachapoyas', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Granada', 'Comisaría Rural', 'E', 'Jr. San Martin S/N', 'Granada', 'Chachapoyas', 'Amazonas', '957-815-705'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Quinjalca', 'Comisaría Rural', 'E', 'Plaza de Armas', 'Quinjalca', 'Chachapoyas', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Leymebamba', 'Comisaría Rural', 'E', 'Jr. Sucre N° 115', 'Leymebamba', 'Chachapoyas', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Durazno Pampa', 'Comisaría Rural', 'E', 'Jr. José Olaya N° 320', 'Chachapoyas', 'Chachapoyas', 'Amazonas', '942-825-762'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Jalca Grande', 'Comisaría Rural', 'E', 'Jr. Alonso de Alvarado N° 774', 'Chachapoyas', 'Chachapoyas', 'Amazonas', '942-824-130'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Balsas', 'Comisaría Rural', 'D', 'Jr. Porvenir N° 125', 'Chachapoyas', 'Chachapoyas', 'Amazonas', '957-815-643'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Sectorial Rodríguez de Mendoza - San Nicolas', 'Comisaría Rural Sectorial', 'B', 'Jr. Huambo N° 316', 'San Nicolas', 'Rodríguez de Mendoza', 'Amazonas', '964-773-975'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Huambo', 'Comisaría Rural', 'E', 'Jr. Porvenir N° 461', 'Huambo', 'Rodríguez de Mendoza', 'Amazonas', '942-808-108'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Limabamba', 'Comisaría Rural', 'D', 'Jr. Alfonso Ugarte S/N', 'Limabamba', 'Rodríguez de Mendoza', 'Amazonas', '957-816-772'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Santa Rosa', 'Comisaría Rural', 'E', 'Jr. Toribio Rodríguez De Mendoza S/N', 'Santa Rosa', 'Rodríguez de Mendoza', 'Amazonas', '957-817-106'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Longar', 'Comisaría Rural', 'E', 'Jr. Gerónimo Meléndez S/N', 'Longar', 'Rodríguez de Mendoza', 'Amazonas', '957-815-679'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Omia', 'Comisaría Rural', 'D', 'Jr. Daniel Alcides Carrión N° 330', 'Omia', 'Rodríguez de Mendoza', 'Amazonas', '957-816-689'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Nuevo Chirimoto', 'Comisaría Rural', 'D', 'Jr. Las Palmas S/N Centro Poblado Nuevo Chirimoto', 'Chirimoto', 'Rodríguez de Mendoza', 'Amazonas', '942-810-408'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Sectorial Bagua Grande - Utcubamba', 'Comisaría Sectorial', 'A', 'Jr. Ricardo Palma N° 200', 'Bagua Grande', 'Utcubamba', 'Amazonas', '957-832-798'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Familia Bagua Grande', 'Comisaría Familia', NULL, 'Jr. Angamos Cdra. 08', 'Bagua Grande', 'Utcubamba', 'Amazonas', '957-815-739'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Naranjitos', 'Comisaría Rural', 'E', 'Fernando Belaunde Terry Km. 248', 'Jamalca', 'Utcubamba', 'Amazonas', '957-818-038'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Corral Quemado', 'Comisaría Rural', 'E', 'Carreta Fernando Belaunde Terry KM 197', 'Bagua Grande', 'Utcubamba', 'Amazonas', '945-319-939'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Jamalca', 'Comisaría Rural', 'E', 'Jr. San Pedro 373', 'Jamalca', 'Utcubamba', 'Amazonas', '957-817-370'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Cumba', 'Comisaría Rural', 'E', 'Jr. Comercio 575', 'Cumba', 'Utcubamba', 'Amazonas', '957-817-581'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Cajaruro', 'Comisaría Rural', 'C', 'Jr. Comercio N° 407', 'Cajaruro', 'Utcubamba', 'Amazonas', '957-817-947'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural El Milagro', 'Comisaría Rural', 'C', 'Av. Ejercito N° 425', 'El Milagro', 'Utcubamba', 'Amazonas', '957-815-026'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Lonya Grande', 'Comisaría Rural', 'E', 'Jr. 28 de Julio N° 346', 'Lonya Grande', 'Utcubamba', 'Amazonas', '957-817-645'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Campo Redondo', 'Comisaría Rural', 'E', 'Camporedondo', 'Camporedondo', 'Luya', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Ocalli', 'Comisaría Rural', 'D', 'Intersección Jr. Loreto 208 y Av. Libertad 805', 'Ocalli', 'Luya', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Sectorial Bagua', 'Comisaría Sectorial', 'B', 'Av. Héroes del Cenepa N° 1000', 'Bagua', 'Bagua', 'Amazonas', '957-815-739'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural La Peca', 'Comisaría Rural', 'E', 'Av. San Felipe N° 217', 'La Peca', 'Bagua', 'Amazonas', '957-815-789'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Copallin', 'Comisaría Rural', 'D', 'Av. San Martin N° 689', 'Copallin', 'Bagua', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural El Muyo', 'Comisaría Rural', 'E', 'Av. Principal N° 446', 'Aramango', 'Bagua', 'Amazonas', '957-815-751'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Aramango', 'Comisaría Rural', 'E', 'Intersección Av. 28 de Julio y Nazaret', 'Aramango', 'Bagua', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Chiriaco', 'Comisaría Rural', 'C', 'Av. Principal N° 306', 'Imaza', 'Bagua', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Imacita', 'Comisaría Rural', 'E', 'Av. Imaza N° 800', 'Imaza', 'Bagua', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Sectorial Lamud', 'Comisaría Sectorial', 'D', 'Jr. Miguel Grau N° 450', 'Lamud', 'Luya', 'Amazonas', '964-775-637'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Luya', 'Comisaría Rural', 'E', 'Jr. San Martin N° 910', 'Luya', 'Luya', 'Amazonas', '957-816-458'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Tingo', 'Comisaría Rural', 'C', 'Jr Bernardo Mejer N° 497', 'Tingo', 'Luya', 'Amazonas', '942-826-926'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Colcamar', 'Comisaría Rural', 'E', 'Jr. 28 de Julio S/N Plaza de Armas', 'Colcamar', 'Luya', 'Amazonas', '942-810-173'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Collonce', 'Comisaría Rural', 'E', 'Collonce S/N Ocumal', 'Ocumal', 'Luya', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Inguilpata', 'Comisaría Rural', 'E', 'Jr. Unión S/N', 'Inguilpata', 'Luya', 'Amazonas', '942-812-403'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Santo Tomas', 'Comisaría Rural', 'E', 'Jr. San Martin N° 383', 'Santo Tomas', 'Luya', 'Amazonas', '957-827-659'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Cocabamba', 'Comisaría Rural', 'E', 'Jr. San José S/N', 'Cocabamba', 'Luya', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Pizuquia – Pueblo Nuevo', 'Comisaría Rural', 'E', 'Anexo de Pueblo Nuevo S/N', 'Pisuquia', 'Luya', 'Amazonas', '957-824-845'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Sectorial Bongara Jazan', 'Comisaría Sectorial', 'B', 'Av. Marginal N° 140', 'Jazan', 'Bongará', 'Amazonas', '980-122-429'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Pomacochas', 'Comisaría Rural', 'C', 'Carretera Fernando Belaunde Terry Km 325 Florida', 'Florida', 'Bongará', 'Amazonas', '957-816-368'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Churuja', 'Comisaría Rural', 'E', 'Carretera Principal Pedro Ruíz - Chachapoyas S/N', 'Jumbilla', 'Bongará', 'Amazonas', '957-815-405'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Jumbilla', 'Comisaría Rural', 'E', 'Jr. Comercio N° 299', 'Jumbilla', 'Bongará', 'Amazonas', '957-816-384'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural San Pablo Valera', 'Comisaría Rural', 'E', 'Jr. Barrio Calvarios S/N', 'Valera', 'Bongará', 'Amazonas', '942-810-875'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Rural Buenos Aires', 'Comisaría Rural', 'E', 'AV. Fernando Belaunde Terry N° 1257', 'Jazan', 'Bongará', 'Amazonas', '964-597-229'),
('Región Policial Amazonas', 'REGPOL Amazonas', 'Comisaría PNP Sectorial Condorcanqui Santa María De Nieva', 'Comisaría Sectorial', 'A', 'Jr Simón Bolívar N° 101', 'Nieva', 'Condorcanqui', 'Amazonas', '980-122-429');

-- ============================================================
-- DATOS: REGPOL PIURA
-- ============================================================
INSERT INTO comisarias_pnp (region, comando_superior, nombre, tipo, categoria, direccion, distrito, provincia, departamento, telefono) VALUES
('Región Policial Piura', 'REGPOL Piura', 'REGPOL Piura', 'Comando', NULL, 'Km 2,5 carretera Piura – Sullana', 'Piura', 'Piura', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Aeropuerto Piura', 'Comisaría', 'V', 'Av. Corpac S/N', 'Castilla', 'Piura', 'Piura', '957-821-448'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Piura', 'Comisaría', 'A', 'Av. Sánchez Cerro', 'Piura', 'Piura', 'Piura', '990-286-068'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Los Algarrobos', 'Comisaría', 'B', 'Asentamiento Los Algarrobos II Etapa Mz D', 'Piura', 'Piura', 'Piura', '945-219-828'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Castilla', 'Comisaría', 'B', 'Av. Corpac N° 100', 'Castilla', 'Piura', 'Piura', '980-121-521'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP San Martin', 'Comisaría', 'B', 'Av. José Carlos Mariátegui 304', '26 de Octubre', 'Piura', 'Piura', '980-121-808'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP El Indio', 'Comisaría', 'C', 'Calle D Asentamiento El Indio', 'Castilla', 'Piura', 'Piura', '990-286-068'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Tácala', 'Comisaría', 'C', 'Av. Los Brillantes Sn Mz. Z Lt.2', 'Castilla', 'Piura', 'Piura', '980-122-489'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP 26 de Octubre', 'Comisaría', 'A', 'Av. Prolongación Grau Mz. C Lote. 19 C.H. Enace I Etapa', '26 de Octubre', 'Piura', 'Piura', '980-121-429'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Familia Piura', 'Comisaría Familia', 'M', 'Calle 9 Urb. La Alborada', 'Piura', 'Piura', 'Piura', '945-218-870'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural La Legua', 'Comisaría Rural', 'D', 'Calle Manuel Vidaurre S/N', 'Catacaos', 'Piura', 'Piura', '964-597-129'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Bellavista de la Unión', 'Comisaría', 'E', 'Calle Piura S/N', 'Bellavista de la Unión', 'Sechura', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Bernal', 'Comisaría Rural', 'D', 'Calle Comercio S/N', 'Bernal', 'Sechura', 'Piura', '964-597-197'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Vice', 'Comisaría Rural', 'D', 'Av. Miguel F. Cerro 100', 'Vice', 'Sechura', 'Piura', '964-597-261'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Puerto Rico', 'Comisaría Rural', 'D', 'Carreta Bayóvar Sechura Parte Alta S/N Km.75', 'Sechura', 'Sechura', 'Piura', '980-121-196'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Sectorial Catacaos', 'Comisaría Rural Sectorial', 'B', 'Av. Francisco Bolognesi S/N', 'Catacaos', 'Piura', 'Piura', '945-265-208'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Parachique', 'Comisaría Rural', 'C', 'Av. Guardia Civil S/N', 'Sechura', 'Sechura', 'Piura', '957-650-465'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Rinconada LLicuar', 'Comisaría Rural', 'D', 'Av. Perú S/N', 'Rinconada LLicuar', 'Piura', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural La Arena', 'Comisaría Rural', 'C', 'Av. Comercio S/N', 'La Arena', 'Piura', 'Piura', '945-247-570'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural La Unión', 'Comisaría Rural', 'C', 'Calle Unión N° 501', 'La Unión', 'Piura', 'Piura', '945-320-143'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Cucungara', 'Comisaría Rural', 'D', 'Av. Grau N° 715', 'Cura Mori', 'Piura', 'Piura', '945-224-677'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Sectorial Sechura', 'Comisaría Sectorial', 'B', 'Calle Sucre 27', 'Sechura', 'Sechura', 'Piura', '945-267-617'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Sectorial Chulucanas', 'Comisaría Rural Sectorial', 'A', 'Jr. Apurímac N° 528', 'Chulucanas', 'Morropón', 'Piura', '945-234-574'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Yapatera', 'Comisaría Rural', 'D', 'C.P. Yapatera', 'Chulucanas', 'Morropón', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Kilometro 50', 'Comisaría Rural', 'D', 'C.P. KM 50', 'Chulucanas', 'Morropón', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural San Jorge', 'Comisaría Rural', 'D', 'Calle Santa Rosa S/N', 'Chulucanas', 'Morropón', 'Piura', '964-596-427'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Talandracas', 'Comisaría Rural', 'D', 'C.P. Talandracas', 'Morropón', 'Morropón', 'Piura', '957-818-806'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural La Matanza', 'Comisaría Rural', 'D', 'Calle 27 de Noviembre S/N', 'La Matanza', 'Morropón', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Sectorial Morropón', 'Comisaría Sectorial', 'A', 'Jr. López N° 101', 'Morropón', 'Morropón', 'Piura', '966-831-209'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Paltashaco', 'Comisaría Rural', 'D', 'Calle Ramon Castilla N° 121 Santa Catalina de Mossa', 'Santa Catalina de Mossa', 'Morropón', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Chalaco', 'Comisaría Rural', 'D', 'Calle Salaverry S/N', 'Chalaco', 'Morropón', 'Piura', '957-818-870'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Yamango', 'Comisaría Rural', 'D', 'Calle Piura S/N', 'Yamango', 'Morropón', 'Piura', '957-821-260'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Buenos Aires', 'Comisaría Rural', 'D', 'Av. Buenos Aires 208', 'Buenos Aires', 'Morropón', 'Piura', '957-816-414'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Santo Domingo', 'Comisaría Rural', 'C', 'Av. 29 de Setiembre N° 203', 'Santo Domingo', 'Morropón', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural San Juan de Bigote', 'Comisaría Rural', 'D', 'Calle Unión Principal S/N', 'San Juan de Bigote', 'Morropón', 'Piura', '957-821-492'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Frías', 'Comisaría Rural', 'D', 'Calle Arequipa N° 224', 'Frías', 'Ayabaca', 'Piura', '943-944-816'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Pacaipampa', 'Comisaría Rural', 'C', 'Calle Progreso S/N', 'Pacaipampa', 'Ayabaca', 'Piura', '964-597-307'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Los Ranchos', 'Comisaría Rural', 'D', 'Calle Comercio Santa Rosa S/N', 'Canchaque', 'Huancabamba', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Huarmaca', 'Comisaría Rural', 'B', 'Av. Centenario N° 390', 'Huarmaca', 'Huancabamba', 'Piura', '964-612-249'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Sondor', 'Comisaría Rural', 'D', 'Av. Huáscar S/N', 'Sondor', 'Huancabamba', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural San Miguel de el Faique', 'Comisaría Rural', 'D', 'Av. Grau N° 102', 'San Miguel de el Faique', 'Huancabamba', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Sondorillo', 'Comisaría Rural', 'D', 'Av. Piura S/N', 'Sondorillo', 'Huancabamba', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Canchaque', 'Comisaría Rural', 'D', 'Calle Progreso N° 201', 'Canchaque', 'Huancabamba', 'Piura', '945-267-617'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Sapalache', 'Comisaría Rural', 'D', 'Jr. San Martin N° 261 Carmen de la Frontera', 'Carmen de la Frontera', 'Huancabamba', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Sullana', 'Comisaría', 'A', 'Jr. San Martin N° 261', 'Sullana', 'Sullana', 'Piura', '964-597-156'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Familia Sullana', 'Comisaría Familia', 'M', 'Av. El Niño Mz C Lt3 Sector B Urb. Popular Nueva Sullana', 'Sullana', 'Sullana', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP El Obrero', 'Comisaría', 'B', 'AA. HH El Obrero', 'Sullana', 'Sullana', 'Piura', '945-262-011'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Bellavista', 'Comisaría', 'B', 'Calle Puno N° 251', 'Bellavista', 'Sullana', 'Piura', '945-191-370'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Tambo grande', 'Comisaría Rural', 'B', 'Jr. Paita N° 759', 'Tambo Grande', 'Piura', 'Piura', '073-293745'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Marcavelica', 'Comisaría Rural', 'C', 'Carretera Panamericana Norte S/N KM. 35', 'Marcavelica', 'Sullana', 'Piura', '980-122-353'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Cruceta', 'Comisaría Rural', 'D', 'Av. Jesús María S/N', 'Tambo Grande', 'Piura', 'Piura', '964-597-130'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Las Lomas', 'Comisaría', 'D', 'Jr. Miguel Grau N° 599', 'Las Lomas', 'Piura', 'Piura', '957-683-815'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Chipillico', 'Comisaría Rural', 'E', 'Av. Progreso S/N', 'Las Lomas', 'Piura', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Suyo', 'Comisaría Rural', 'C', 'Jr. Lima N° 548', 'Suyo', 'Ayabaca', 'Piura', '957-818-940'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Sectorial Ayabaca', 'Comisaría Sectorial', 'B', 'Calle Arica N° 103', 'Ayabaca', 'Ayabaca', 'Piura', '957-649-650'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Jilili', 'Comisaría Rural', 'D', 'Av. Grau N° 103', 'Jilili', 'Ayabaca', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Montero', 'Comisaría Rural', 'D', 'Jr. Piura N° 948', 'Montero', 'Ayabaca', 'Piura', '945-237-003'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Sapillica', 'Comisaría Rural', 'D', 'Frente a la Plaza de Armas', 'Sapillica', 'Ayabaca', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Paimas', 'Comisaría Rural', 'D', 'Av. Fernando Belaunde Terry N° 300', 'Paimas', 'Ayabaca', 'Piura', '945-261-556'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Tondopa', 'Comisaría Rural', 'D', 'Av. Puente Tondopa S/N', 'Lagunas', 'Ayabaca', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Sicchez', 'Comisaría Rural', 'D', 'Calle Piura S/N', 'Sicchez', 'Ayabaca', 'Piura', '980-122-295'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Sectorial Querocotillo', 'Comisaría Rural Sectorial', 'C', 'Calle Rodríguez N° 485', 'Querocotillo', 'Sullana', 'Piura', '945-307-039'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Los Encuentros de Pilares', 'Comisaría Rural', 'D', 'carretera Sullana - Los encuentros', 'Lancones', 'Sullana', 'Piura', '980-121-523'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Miguel Checa', 'Comisaría Rural', 'D', 'Av. La Victoria N° 332', 'Miguel Checa', 'Sullana', 'Piura', '957-820-235'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Lancones', 'Comisaría Rural', 'D', 'Plaza de Armas S/N', 'Lancones', 'Sullana', 'Piura', '945-263-865'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural San Jacinto', 'Comisaría Rural', 'D', 'Carretera Panamericana Norte S/N Ignacio Escudero', 'Ignacio Escudero', 'Sullana', 'Piura', '945-237-492'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Salitral', 'Comisaría Rural', 'D', 'Av. Transversal 27 Octubre', 'Salitral', 'Sullana', 'Piura', '945-266-832'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Vichayal', 'Comisaría Rural', 'D', 'Av. Mariscal Castilla N° 227', 'Vichayal', 'Paita', 'Piura', '957-821-087'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Pueblo Nuevo de Colan', 'Comisaría Rural', 'D', 'Av. Sánchez Cerro S/N', 'Colan', 'Paita', 'Piura', '964-615-537'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Sectorial Paita', 'Comisaría Sectorial', 'A', 'Jr. Independencia N° 417', 'Paita', 'Paita', 'Piura', '945-237-003'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Amotape', 'Comisaría Rural', 'D', 'Calle San Martin 200', 'Amotape', 'Paita', 'Piura', '945-247-640'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural San Lucas de Colan', 'Comisaría Rural', 'D', 'Av. Sánchez Cerro S/N', 'Colan', 'Paita', 'Piura', '964-597-158'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural La Huaca', 'Comisaría Rural', 'D', 'Calle Ferrocarril N° 368', 'La Huaca', 'Paita', 'Piura', '957-818-653'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Tamarindo', 'Comisaría Rural', 'D', 'Calle Alfonso Ugarte S/N', 'Tamarindo', 'Paita', 'Piura', '945-236-806'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Sectorial Talara', 'Comisaría Sectorial', 'A', 'Av. Bolognesi S/N Pirañas', 'Talara', 'Talara', 'Piura', '980-121-520'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Talara Alta', 'Comisaría Rural', 'B', 'Av. A 55 Pirañas', 'Talara', 'Talara', 'Piura', '939-108-348'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Los Órganos', 'Comisaría Rural', 'C', 'Carretera Panamericana Norte S/N', 'Los Órganos', 'Talara', 'Piura', '980-122-347'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural Máncora', 'Comisaría Rural', 'C', 'AV. Piura N° 657', 'Máncora', 'Talara', 'Piura', '980-121-524'),
('Región Policial Piura', 'REGPOL Piura', 'Comisaría PNP Rural El Alto', 'Comisaría Rural', 'D', 'Av. Bolognesi S/N', 'El Alto', 'Talara', 'Piura', '957-820-746');